apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-app
        image: krishna820/mongo-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://admin:password@mongo:27017/
